# Begin integrating PyMARE into NiMARE

In [1]:
import numpy as np

import nimare as nim
import pymare

200624-14:14:36,964 nipype.utils INFO:
	 Running nipype version 1.4.2 (latest: 1.5.0)


INFO:nipype.utils:Running nipype version 1.4.2 (latest: 1.5.0)


In [2]:
dset = nim.dataset.Dataset('/Users/tsalo/Documents/tsalo/NiMARE/nimare/tests/data/nidm_pain_dset.json')
dset.update_path('/Users/tsalo/.nimare/nidm_21pain')

# Calculate varcopes from se maps
dset.images = nim.transforms.transform_images(dset.images, target='varcope', masker=dset.masker)

INFO:nimare.utils:Shared path detected: "/Users/tsalo/.nimare/nidm_21pain/"
INFO:nimare.utils:Shared path detected: "/Users/tsalo/.nimare/nidm_21pain/"


In [3]:
# Get maps
beta_maps = dset.masker.transform(dset.get_images(imtype='beta'))
varcope_maps = dset.masker.transform(dset.get_images(imtype='varcope'))

In [4]:
# Note the zeros due to mask mismatch
beta_maps

array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         4.9952388e-02,  3.6424603e-02,  7.7398606e-02],
       ...,
       [ 1.6634607e+01,  8.0900936e+00,  4.2870326e+00, ...,
        -6.9481072e+00, -4.4550176e+00, -9.5353413e+00],
       [ 7.3258469e+01,  7.6597244e+01,  6.4972069e+01, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 1.3388044e+00, -2.6281266e+00, -9.5338631e+00, ...,
        -3.2507526e+01, -3.8365864e+01, -2.9402128e+01]], dtype=float32)

In [5]:
# Note the zeros due to mask mismatch
varcope_maps

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.26488643e-03, 2.92396181e-03, 5.67109000e-03],
       ...,
       [2.48594711e+02, 1.58459198e+02, 1.13961449e+02, ...,
        1.01716537e+02, 8.32753525e+01, 6.97489929e+01],
       [1.21737695e+03, 1.06643811e+03, 1.01201697e+03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.35399414e+02, 2.33372375e+02, 2.28151337e+02, ...,
        1.64790924e+02, 1.75629776e+02, 1.81595764e+02]])

In [6]:
est = pymare.estimators.DerSimonianLaird()
pymdata = pymare.Dataset(y=beta_maps, v=varcope_maps)
est.fit(pymdata)
est_summary = est.summary()

/Users/tsalo/Documents/tsalo/PyMARE/pymare/stats.py:23: RuntimeWarning: divide by zero encountered in true_divide
  w = 1. / (v + tau2)
/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1965: RuntimeWarning: invalid value encountered in greater
  large = s > cutoff
/Users/tsalo/Documents/tsalo/PyMARE/pymare/estimators/estimators.py:177: RuntimeWarning: divide by zero encountered in true_divide
  w = 1. / v


In [7]:
est_summary.tau2

array([nan, nan, nan, ..., nan, nan, nan])

In [8]:
est_summary.get_re_stats()

/Users/tsalo/Documents/tsalo/PyMARE/pymare/results.py:73: UserWarning: Method 'QP' is not parallelized; it may take a while to compute CIs for 228453 parallel tau^2 values.
  "compute CIs for {} parallel tau^2 values.".format(n_iters))
/Users/tsalo/Documents/tsalo/PyMARE/pymare/stats.py:23: RuntimeWarning: divide by zero encountered in true_divide
  w = 1. / (v + tau2)
/Users/tsalo/Documents/tsalo/PyMARE/pymare/stats.py:116: RuntimeWarning: divide by zero encountered in true_divide
  w = 1. / (v + tau2)


ValueError: Value of tau^2 must be >= 0.