# Begin integrating PyMARE into NiMARE

In [1]:
import numpy as np

import nimare as nim
import pymare

200625-14:06:16,579 nipype.utils INFO:
	 Running nipype version 1.4.2 (latest: 1.5.0)


INFO:nipype.utils:Running nipype version 1.4.2 (latest: 1.5.0)


In [2]:
dset = nim.dataset.Dataset('/Users/tsalo/Documents/tsalo/NiMARE/nimare/tests/data/nidm_pain_dset.json')
dset.update_path('/Users/tsalo/.nimare/nidm_21pain')

# Calculate varcopes from se maps
dset.images = nim.transforms.transform_images(dset.images, target='varcope', masker=dset.masker)

INFO:nimare.utils:Shared path detected: "/Users/tsalo/.nimare/nidm_21pain/"
INFO:nimare.utils:Shared path detected: "/Users/tsalo/.nimare/nidm_21pain/"


In [107]:
# Get maps
beta_maps = dset.masker.transform(dset.get_images(imtype='beta'))
varcope_maps = dset.masker.transform(dset.get_images(imtype='varcope'))
beta_vals = beta_maps[:, 500]
varcope_vals = varcope_maps[:, 500]

In [86]:
# Note the zeros due to mask mismatch
beta_maps

array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         4.9952388e-02,  3.6424603e-02,  7.7398606e-02],
       ...,
       [ 1.6634607e+01,  8.0900936e+00,  4.2870326e+00, ...,
        -6.9481072e+00, -4.4550176e+00, -9.5353413e+00],
       [ 7.3258469e+01,  7.6597244e+01,  6.4972069e+01, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 1.3388044e+00, -2.6281266e+00, -9.5338631e+00, ...,
        -3.2507526e+01, -3.8365864e+01, -2.9402128e+01]], dtype=float32)

In [87]:
beta_maps = np.zeros((beta_maps.shape[0], 5))
# missing values in all studies
beta_maps[:, 0] = np.nan
# all zeros in all studies
beta_maps[:, 1] = 0
# missing values or zeros in all studies
beta_maps[:5, 2] = np.nan
beta_maps[5:, 2] = 0
# missing values in some studies
beta_maps[:5, 3] = np.nan
beta_maps[5:, 3] = np.random.random(size=beta_maps[5:, :].shape[0])
# values in all studies
beta_maps[:, 4] = beta_vals

In [88]:
# Note the zeros due to mask mismatch
varcope_maps = np.random.random(beta_maps.shape)
varcope_maps[:, 0] = np.nan
varcope_maps[:, 1] = 0
varcope_maps[:5, 2] = np.nan
varcope_maps[5:, 2] = 0
# missing values in some studies
varcope_maps[:5, 3] = np.nan
varcope_maps[5:, 3] = np.random.random(size=varcope_maps[5:, :].shape[0])
# values in all studies
varcope_maps[:, 4] = varcope_vals

In [108]:
beta_vals[0] = 0
#varcope_vals[0] = 0
pymdata = pymare.Dataset(y=beta_vals, v=varcope_vals)

In [109]:
pymdata.y[:, -1]

array([ 0.0000000e+00,  1.8545592e-02, -1.8239343e-01,  9.2357084e-02,
       -1.5175854e+00,  2.2288015e-01,  3.7830898e-01, -1.5596311e-01,
       -6.1550317e+00, -1.0623064e+01, -7.2810631e+00, -1.7402008e+01,
       -4.8586643e+01, -2.5317017e+01, -2.5451143e+02, -8.8065613e+02,
        3.5712410e+01, -8.4780434e+01, -5.7234497e+01,  6.2319660e+01,
       -6.2231270e+01], dtype=float32)

In [110]:
pymdata.v[:, -1]

array([2.89738581e-02, 3.14901288e-02, 2.00873977e-02, 1.50731778e-02,
       1.97102654e+00, 9.37494571e-01, 1.15110459e+00, 5.72463739e+00,
       2.31791263e+00, 4.61700461e+00, 5.86888184e+03, 2.97981567e+02,
       2.47385788e+02, 1.27876550e+03, 2.81807812e+04, 7.12048047e+04,
       8.31162793e+03, 1.21666357e+04, 1.79912061e+03, 3.84692236e+03,
       5.20082214e+02])

In [111]:
est = pymare.estimators.DerSimonianLaird()
est.fit(pymdata)
est_summary = est.summary()

In [114]:
est_summary.get_re_stats()

{'ci_l': array([], dtype=float64),
 'ci_u': array([], dtype=float64),
 'tau^2': array([0.43365403])}

In [113]:
est_summary.tau2

array([0.43365403])

In [ ]:
beta_maps[:, 187]

In [ ]:
varcope_maps[:, 187]

In [ ]:
import numpy as np
from pymare.stats import q_profile
y = np.array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, -5.2165329e-01, 7.4963748e-01, 3.3219385e-01, -1.2351226e+00, 1.7527617e+00, -3.0110748e+00,  1.0946554e+02, -4.8926108e-02, 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -6.2120113e+01, -2.8613630e+01, -1.2308966e+01,  5.3221474e+00,  0.0000000e+00, -9.2870388e+00])
v = np.array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.54480810e-01, 1.21734442e-01, 2.25415160e-01, 1.74327830e+00, 6.00752247e-01, 1.43908420e+00, 3.25888647e+03, 4.66549950e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.91479907e+03, 2.15909521e+03, 2.17931152e+03, 1.63775589e+02, 0.00000000e+00, 1.01077698e+02])
X = np.array([[1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.]])
alpha = 0.05
q_cis = q_profile(y=y, X=X, v=v, alpha=alpha)

In [ ]:
import scipy.stats as ss
k, p = X.shape
df = k - p
l_crit = ss.chi2.ppf(1 - alpha / 2, df)
u_crit = ss.chi2.ppf(alpha / 2, df)

In [ ]:
u_crit