In [1]:
import numpy as np
from numpy import ma
from pymare import core, estimators

In /Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.


In [2]:
n_studies = 110
v = np.random.normal(5, 2, size=(n_studies))
y = np.random.normal(10, 3, size=(n_studies))
X = np.ones(n_studies)
n = np.random.randint(5, 50, size=n_studies)

mask = np.zeros(n_studies, int)
mask[:10] = 1
mask = mask.astype(bool)
mv = ma.masked_array(v, mask)
mX = ma.masked_array(X, mask)
my = ma.masked_array(y, mask)
mn = ma.masked_array(n, mask)

In [3]:
dataset_full = core.Dataset(v=v, X=X, y=y, n=n, add_intercept=False)
dataset_red = core.Dataset(v=v[~mask], X=X[~mask], y=y[~mask], n=n[~mask], add_intercept=False)
dataset_masked = core.Dataset(v=mv, X=mX, y=my, n=mn, add_intercept=False)
dataset_masked.X = mX[:, None]
dataset_masked.v = mv[:, None]
dataset_masked.y = my[:, None]
dataset_masked.n = mn[:, None]

In [4]:
est = estimators.WeightedLeastSquares().fit(dataset_full)
results = est.summary()
print(results.to_df())

[[0.25366459]
 [0.1904396 ]
 [0.1635258 ]
 [0.16833568]
 [0.30195398]
 [0.21516058]
 [0.22551783]
 [0.23850513]
 [0.31313639]
 [0.18379974]
 [0.37451036]
 [0.22993118]
 [0.14698924]
 [0.16506344]
 [0.23378934]
 [0.12913571]
 [0.27045722]
 [0.25512905]
 [0.36863533]
 [0.14690322]
 [0.22487467]
 [0.46509415]
 [0.27602824]
 [0.31957155]
 [0.15330524]
 [0.21671167]
 [0.17142887]
 [0.32004526]
 [0.24221313]
 [0.2684226 ]
 [0.27275703]
 [0.16047333]
 [0.12771826]
 [0.15040563]
 [0.18787076]
 [0.204944  ]
 [0.13264648]
 [0.20543436]
 [0.1214328 ]
 [0.23451644]
 [0.2105268 ]
 [0.12498401]
 [0.24474368]
 [0.20041386]
 [0.16197852]
 [0.34978904]
 [0.15591327]
 [0.11792559]
 [0.16361333]
 [0.12361372]
 [0.11443032]
 [0.21854636]
 [0.23554783]
 [0.2383196 ]
 [0.2270172 ]
 [0.24625371]
 [0.4206356 ]
 [0.75240464]
 [0.09166908]
 [0.23149339]
 [0.24599857]
 [0.14838249]
 [0.22114309]
 [0.16593294]
 [0.17900642]
 [0.24430833]
 [0.16338089]
 [0.14211403]
 [0.71704605]
 [0.13781047]
 [0.19997175]
 [0.21

In [5]:
est = estimators.WeightedLeastSquares().fit(dataset_red)
results = est.summary()
print(results.to_df())

[[0.37451036]
 [0.22993118]
 [0.14698924]
 [0.16506344]
 [0.23378934]
 [0.12913571]
 [0.27045722]
 [0.25512905]
 [0.36863533]
 [0.14690322]
 [0.22487467]
 [0.46509415]
 [0.27602824]
 [0.31957155]
 [0.15330524]
 [0.21671167]
 [0.17142887]
 [0.32004526]
 [0.24221313]
 [0.2684226 ]
 [0.27275703]
 [0.16047333]
 [0.12771826]
 [0.15040563]
 [0.18787076]
 [0.204944  ]
 [0.13264648]
 [0.20543436]
 [0.1214328 ]
 [0.23451644]
 [0.2105268 ]
 [0.12498401]
 [0.24474368]
 [0.20041386]
 [0.16197852]
 [0.34978904]
 [0.15591327]
 [0.11792559]
 [0.16361333]
 [0.12361372]
 [0.11443032]
 [0.21854636]
 [0.23554783]
 [0.2383196 ]
 [0.2270172 ]
 [0.24625371]
 [0.4206356 ]
 [0.75240464]
 [0.09166908]
 [0.23149339]
 [0.24599857]
 [0.14838249]
 [0.22114309]
 [0.16593294]
 [0.17900642]
 [0.24430833]
 [0.16338089]
 [0.14211403]
 [0.71704605]
 [0.13781047]
 [0.19997175]
 [0.21074326]
 [0.26100623]
 [0.20333747]
 [0.15653637]
 [0.20283301]
 [0.19596723]
 [0.18734003]
 [0.18195002]
 [0.18581607]
 [0.20851598]
 [0.32

In [6]:
est = estimators.WeightedLeastSquares().fit(dataset_masked)
results = est.summary()
print(results.to_df())

[[--]
 [--]
 [--]
 [--]
 [--]
 [--]
 [--]
 [--]
 [--]
 [--]
 [0.3745103648356675]
 [0.22993117590047088]
 [0.146989239664625]
 [0.16506344393688638]
 [0.2337893355126558]
 [0.1291357056591504]
 [0.2704572210292129]
 [0.25512905068601716]
 [0.3686353284240596]
 [0.14690322043402915]
 [0.22487466571756395]
 [0.4650941454442938]
 [0.2760282360723464]
 [0.31957154782219754]
 [0.1533052374552003]
 [0.21671167320109663]
 [0.17142887084261058]
 [0.32004525624566094]
 [0.24221312937814005]
 [0.268422598793479]
 [0.27275703339041674]
 [0.16047332687887986]
 [0.12771825770500342]
 [0.15040563019497658]
 [0.18787076335909433]
 [0.2049439963557213]
 [0.13264648443683763]
 [0.20543435908691862]
 [0.12143279541367824]
 [0.23451644443190856]
 [0.21052680423710907]
 [0.1249840116147483]
 [0.2447436840816702]
 [0.20041386123676985]
 [0.16197852111930422]
 [0.34978903953998397]
 [0.15591327023720983]
 [0.11792558913800755]
 [0.16361332724672953]
 [0.12361372430584389]
 [0.24599857127963956]
 [0.14838248

In [7]:
from pymare.stats import ensure_2d

In [8]:
np.array(mX)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
ensure_2d(my).shape

(110, 1)

In [26]:
arr1 = my[None, :]
arr2 = np.random.random(my.shape)[:, None]

vals = arr2.dot(arr1)
vals2 = arr1.T.dot(arr2.T)

In [27]:
vals.shape

(110, 110)

In [28]:
vals2

masked_array(
  data=[[--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        ...,
        [3.05250974655557, 6.547407258512872, 7.234573144765092, ...,
         1.6517030945990963, 1.229771943202288, 11.61084713551559],
        [2.494060456547484, 5.349574904648596, 5.911025450686637, ...,
         1.349528000310259, 1.0047881346073693, 9.48667067824541],
        [3.22955193763616, 6.927149642055488, 7.6541703901227125, ...,
         1.7475000483065761, 1.301097356528042, 12.284263434838797]],
  mask=[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],
  fill_value=1e+20)

In [39]:
np.array_equal(np.dot(arr1, arr2), arr1.dot(arr2))

False

In [46]:
np.dot(arr1, arr1.T)

masked_array(data=[[11387.77893375]],
             mask=False,
       fill_value=1e+20)

In [45]:
arr1.dot(arr1.T)

masked_array(data=[[10064.306048215294]],
             mask=[[False]],
       fill_value=1e+20)